---
- name: Install PHP dependencies
  composer:
    command: install
    working_dir: "{{ project_dir }}"
    no_dev: "{{ (stage == 'production') | ternary('Yes','No') }}"
    optimize_autoloader: "yes"

- name: Install JavaScript dependencies
  npm:
    path: "{{ project_dir }}"

- name: Compile JavaScript
  command: npm run build-js
  args:
    chdir: "{{ project_dir }}"

- name: Remove node modules
  file:
    path: "{{ project_dir }}/node_modules"
    state: absent
  when: stage != "dev"
